torchrun --nproc_per_node=1 --master_port=20001 ~/FastChat/fastchat/train/train_mem.py \
    --model_name_or_path ~/.cache/huggingface/hub/models--jphme--Llama-2-13b-hf
    --data_path ~/traindata/translated_tasks_de_deepl_12k.json \
    --bf16 True \
    --output_dir output_vicuna \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1200 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True